### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by LJYsix** [bee992/Text-Manipulation-Classification#1]
您好！我是一个深度学习的初学者，想通过这个项目实践一下。但是目前天池官网上这个比赛已经结束，无法下载数据集了。
请问您是否能够提供给我一份数据集？感激不尽！

**Comment by bee992** [comment]
LJYsix，您好。根据天池官方的比赛协议，我无法私下提供数据集给您，您可以通过其他途径获取类似的开源篡改数据集，同样也可以达到实践的目的，祝好！
